/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAttachmentsAttachmentIdRouteImport } from './routes/api/attachments/$attachmentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTasksTaskIdAttachmentsRouteImport } from './routes/api/tasks/$taskId/attachments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsAttachmentIdRoute =
  ApiAttachmentsAttachmentIdRouteImport.update({
    id: '/api/attachments/$attachmentId',
    path: '/api/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdAttachmentsRoute =
  ApiTasksTaskIdAttachmentsRouteImport.update({
    id: '/api/tasks/$taskId/attachments',
    path: '/api/tasks/$taskId/attachments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AppAppRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tasks/$taskId/attachments': typeof ApiTasksTaskIdAttachmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AppAppRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tasks/$taskId/attachments': typeof ApiTasksTaskIdAttachmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/app': typeof AppAppRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tasks/$taskId/attachments': typeof ApiTasksTaskIdAttachmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/sign-up'
    | '/sitemap.xml'
    | '/app'
    | '/settings'
    | '/api/health'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/tasks/$taskId/attachments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/sign-up'
    | '/sitemap.xml'
    | '/app'
    | '/settings'
    | '/api/health'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/tasks/$taskId/attachments'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/sign-up'
    | '/sitemap.xml'
    | '/_app/app'
    | '/_app/settings'
    | '/api/health'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/tasks/$taskId/attachments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAttachmentsAttachmentIdRoute: typeof ApiAttachmentsAttachmentIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTasksTaskIdAttachmentsRoute: typeof ApiTasksTaskIdAttachmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$attachmentId': {
      id: '/api/attachments/$attachmentId'
      path: '/api/attachments/$attachmentId'
      fullPath: '/api/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId/attachments': {
      id: '/api/tasks/$taskId/attachments'
      path: '/api/tasks/$taskId/attachments'
      fullPath: '/api/tasks/$taskId/attachments'
      preLoaderRoute: typeof ApiTasksTaskIdAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAttachmentsAttachmentIdRoute: ApiAttachmentsAttachmentIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTasksTaskIdAttachmentsRoute: ApiTasksTaskIdAttachmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
